# Copyright (c) 2024-2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: "Docker"
on:
  workflow_call:
    inputs:
      version:
        description: "Application version (e.g. v1.0.0)"
        type: string
        required: true
      context:
        description: "Docker build context"
        type: string
        default: "${{ github.workspace }}"
      platforms:
        description: "Platforms to build image for (newline/comma separated)"
        type: string
        default: "linux/amd64"
      file:
        description: "Dockerfile to build"
        type: string
        default: "${{ github.workspace }}/Dockerfile"
      tags:
        description: "Docker image tags (newline/comma separated)"
        type: string
        required: true
      build-args:
        description: "Additional Docker build args (built-in: VERSION, VCS_REF, BUILD_DATE)"
        type: string
        default: ""
      prebuild:
        description: "Commands to execute before building Docker image (WARNING: This will be executed as a shell command!)"
        type: string
      dockerhub:
        description: "Push to Docker Hub (requires secrets to be set)"
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        required: false
      DOCKERHUB_PASSWORD:
        description: "Docker Hub authentication token"
        required: false

permissions:
  contents: read

jobs:
  docker:
    name: "Build and push"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Container Registry
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: "Login to DockerHub"
        if: inputs.dockerhub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Prepare to build"
        id: "prepare"
        run: |
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: "Pre-build"
        if: inputs.prebuild != ''
        run: "${{ inputs.prebuild }}" # zizmor: ignore[template-injection] # inputs.prebuild is trusted from calling workflow.

      - name: "Build and push"
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "${{ inputs.context }}"
          platforms: "${{ inputs.platforms }}"
          file: "${{ inputs.file }}"
          push: true
          build-args: |
            VERSION=${{ inputs.version }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.build_date }}
            ${{ inputs.build-args }}
          tags: "${{ inputs.tags }}"
