# Copyright (c) 2024-2026 Hemi Labs, Inc.
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

name: JS Checks

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: Number of commits to fetch. 0 indicates all history for all branches and tags.
        default: 1
        type: number
      node-versions:
        description: Array of Node versions to test with (JSON string)
        default: "['']"
        type: string

permissions:
  contents: read

jobs:
  run-checks:
    name: "run-checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: hemilabs/actions/setup-node-env@8f87619b7f0122c39e14a32514ab3e4e0d4c3966 # v2.3.0
      - run: npm run --if-present format:check
      - run: npm run --if-present lint
      - run: npm run --if-present --include-workspace-root --workspaces deps:check
      - run: npm run --if-present --include-workspace-root --workspaces build

  run-tests:
    name: "run-tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJSON(inputs.node-versions) }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          fetch-depth: ${{ inputs.fetch-depth }}
      - uses: hemilabs/actions/setup-node-env@8f87619b7f0122c39e14a32514ab3e4e0d4c3966 # v2.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run --if-present --include-workspace-root --workspaces test
